---
# Nome do arquivo PDF gerado na pasta resultado
output-file: "Entrega 3"
---

```{r setup}
#| include: false
source("rdocs/entrega_3.R")
```

```{r}
# Rodar apenas uma vez na vida!
## Instalando o tinytex(pacote apenas)
### CRAN version
#install.packages('tinytex')


## Baixando o tinytex
library(tinytex)
#tinytex::install_tinytex()
```




# Objetivo

Esse template foi criado para o alocado conseguir observar como ficaria sua análise o arquivo principal. É daqui que o gerente de projetos irá copiar a análise e inserir no documento principal que gerará o relatório estatístico.

# Análises

## Análise 5

## Análise dos perfis das idades dos clientes paracada loja da cidade de Âmbar Seco.

```{r}
#| label: fig-
#| fig-cap: "Boxplot da idade (anos) pelo número da loja de Âmbar Seco"
box


```






::: {#quad- layout-align="center" quad-pos="H"}
```{=latex}
\begin{quadro}[H]
	\setlength{	\tabcolsep}{9pt}
	\renewcommand{	\arraystretch}{1.20}
	\caption{Medidas resumo da(o) [nome da variável]}
	\centering
	\begin{adjustbox}{max width=\textwidth}
	\begin{tabular} { | l |
			S[table-format = 2.2]
			S[table-format = 2.2]
			S[table-format = 3.2]
			S[table-format = 2.2]
			|}
	\hline
		\textbf{Estatística} & \textbf{2} & \textbf{6} & \textbf{8} & \textbf{9} \\
		\hline
		Média & 34,99 & 39,76 & 35,64 & 33,95 \\
		Desvio Padrão & 5,47 & 6,05 & 12 & 13,51 \\
		Variância & 29,91 & 36,64 & 144,12 & 182,54 \\
		Mínimo & 25 & 30 & 15 & 16 \\
		1º Quartil & 31 & 34 & 27 & 24 \\
		Mediana & 34 & 40 & 34 & 31 \\
		3º Quartil & 40 & 44 & 39 & 39 \\
		Máximo & 44 & 49 & 77 & 80 \\
	\hline
	\end{tabular}
	\label{quad:quadro_resumo1}
	\end{adjustbox}
\end{quadro}
```

Medidas resumo da 
:::



::: {#tbl-modalidades layout-align="center" tbl-pos="H"}
```{=latex}

```
